name: adila
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - pip
  - pandas
  - scikit-learn
  - tqdm
  - pip:
    - pytrec-eval-terrier==0.5.2
    - reranking==0.3.6
    - torch==1.13.0
    - seaborn
